### ISSUE TITLE
Handle error in i/o id calculation (v0.10)

### ISSUE THREAD

**Issue by krl** [dusk-network/microkelvin#104]
**Describe what you want implemented** 
At the moment i/o errors in Link id calculations are panics, it would be nice to handle these errors more elegantly.

**Describe "Why" this is needed**
Even though i/o errors in general are non-recoverable, it would be nice to handle this more elegantly.

**Describe alternatives you've considered**
Just leaving the panic as it's not recoverable.

**Additional context**
We might just deprecate 0.10 before we get to this.

**Comment by autholykos** [comment]
Closing as obsolete
