### ISSUE TITLE
Conversion between annotated types

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/microkelvin#24]
Provided you have the following constraints
* `L` as the leaf
* `A` as a given annotation
* `S` as an implementation of `Store`
* `X` as an implementation of `Compound<S>`, being `X::Leaf = L` and `X:Annotation = A`
* `Y` as an implementation of `Compound<S>`, being `X::Leaf = L` and `X:Annotation = A`

In one scenario, consider `X` as a wrapper type for `Y`.

If you don't have the ability to convert an `Annotated<Y, S>` to `Annotated<X, S>`, you cannot encapsulate the compound implementation of `Y` over `X`.

## Proposed change

Provided `S: Store`, implement a conversion between `Annotated<Y, S>` to `Annotated<X, S>` if, and only if:
* `X::Leaf == Y::Leaf`
* `X::Annotation == Y::Annotation`

**Comment by vlopes11** [comment]
The resolution of this issue should trigger an update over https://github.com/dusk-network/Poseidon252/blob/master/src/tree/mod.rs on the `Compound` implementation for `PoseidonTree`

**Comment by krl** [comment]
@vlopes11 agreed that this is deprecated?
