### ISSUE TITLE
`MaxKey` should implement `PartialOrd<K>`

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/microkelvin#52]
The purpose of a max key annotation is to compare to some given key to implement the data structure logic.

Since we don't have a native implementation of `PartialOrd<K>`, then it is always mandatory to add unrelated boilerplate code on the data structure implementations.

The implementation of a generic `PartialOrd` is trivial and should

* If `MaxKey::Maximum(k)`, return `k.partial_cmp(arg)`
* If `MaxKey::NegativeInfinity`, return `Ordering::Less`

**Comment by ureeves** [comment]
`MaxKey` already implements PartialOrd<K>
