### ISSUE TITLE
Implement on-disk persistence layer

### ISSUE THREAD

**Issue by autholykos** [dusk-network/microkelvin#75]
**Describe what you want implemented** 
I want to be able to persist Microkelvin's storage on disk

**Describe "Why" this is needed**
Because otherwise the VM needs to be always on

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ureeves** [comment]
Closed by [this](https://github.com/dusk-network/microkelvin/pull/79) PR.
