### ISSUE TITLE
Allow for querying the root of the tree

### ISSUE THREAD

**Issue by ureeves** [dusk-network/microkelvin#85]
**Describe what you want implemented** 
We should add a method for querying the root of the tree.

**Describe "Why" this is needed**
In `rusk` we need to offer a node the root of the state when transactions are applied. See this [issue](https://github.com/dusk-network/rusk-vm/issues/265).

**Describe alternatives you've considered**
We currently use the `Store::hash`and `EncodeToVec`to compute the state root every time the state is queried. This is horribly slow.

**Comment by miloszm** [comment]
PR 101 from Kris should fix the issue

**Comment by autholykos** [comment]
Obsolete
