### ISSUE TITLE
Implement mmap-backed version of HostStore

### ISSUE THREAD

**Issue by miloszm** [dusk-network/microkelvin#86]
**Describe what you want implemented** 
mmap (file) backed version of HostStore, which currently only implements memory version of storage (serialisation)

**Describe "Why" this is needed**
It is needed for the persist/restore functionality of microkelvin-backed tree-like data structures

**Describe alternatives you've considered**
Host executing code with tree-like data structures needs persistence, alternative would be a different kind of persistence, yet file-based is most feasible

**Additional context**
this issue is based on PR 84 "Storage trait and Store refactor", branch "reset_branch_ref"

**Comment by krl** [comment]
fixed by #90
