### ISSUE TITLE
Move host storage tests to new HostStore and fix error in HostStore

### ISSUE THREAD

**Issue by miloszm** [dusk-network/microkelvin#89]
**Describe what you want implemented** 
Move host storage tests to new HostStore and provide proper test coverage for the new HostStore. 
Fix errors in HostStore detected by the tests.

**Describe "Why" this is needed**
Same and extended tests as for the old host storage are needed in the new HostStore implementation.

**Describe alternatives you've considered**
N/A

**Additional context**
New implementation should satisfy similar tests as the old implementation. Currently the new implementation has no tests.
Also tests need to be done for the restore functionality.

Also needs to be done:
Fix PageStorage get function for offsets being multiplies of page size.
Panic happens for offsets being multiplies of page size, for example for offset 262144 being 4 * 65536 (where 65536 is a page size) there is a panic inside get method of Storage trait of PageStorage.
Tests moved from host detect this problem.

**Comment by krl** [comment]
fixed by #90
