### ISSUE TITLE
The persist method should accept a closure instead of a function pointer.

### ISSUE THREAD

**Issue by ZER0** [dusk-network/microkelvin#94]
**Describe what you want implemented** 
The persist method should accept a closure instead of a function pointer.

**Describe "Why" this is needed**
The persistence feature does not allow using a closure, but only a function pointer. This limits a lot how we can interact with the serialization of the data on disk, since we cannot access to any variable from the outer scope.

**Describe alternatives you've considered**
Duplicate everything inside the function pointer we're passing to the persist method. This is kind of work-ish at the moment, but it's not ideal.

**Additional context**
N/A

**Comment by ZER0** [comment]
This was partially added in #95 but still not working as intended.

**Comment by autholykos** [comment]
Obsolete
