### ISSUE TITLE
Add a test to reproduce the `CanonError::NotFound` issue we have in `Rusk`

### ISSUE THREAD

**Issue by ZER0** [dusk-network/microkelvin#97]
**Describe what you want implemented** 
As we noticed in Rusk during the integration of Rusk-VM, we have an issue when the instance of the VM is used across threads. We isolated that issue to how microkelvin handle the data, using Canonical as store.
We should have a test in Microkelvin that reproduce that without the whole infrastructure of Rusk.

**Describe "Why" this is needed**
To have a isolated way to reproduce the issue, and so fix it.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by autholykos** [comment]
Obsolete
